# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/RVfpga/RiscV/Lab5/Lab5/.Xil/Vivado-17656-MSI/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include
    D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/include
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/gpio
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/ptc
    D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/WishboneInterconnect
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/uart
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi
    D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/BootROM/sw
  } {
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/include/common_defines.vh
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/cf_math_pkg.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/addr_decode.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_pkg.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_atop_filter.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_cdc.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_demux.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_err_slv.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_id_prepend.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/axi_intercon.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_intf.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_mux.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_xbar.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lib/beh_lib.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/binary_to_gray.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/bscan_tap.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/cdc_fifo_gray.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/counter.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/dbg/dbg.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/include/swerv_types.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/dec/dec.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/dec/dec_decode_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/dec/dec_gpr_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/dec/dec_ib_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/dec/dec_tlu_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/dec/dec_trigger.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/delta_counter.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/dma/dma_ctrl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/exu/exu.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/exu/exu_alu_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/exu/exu_div_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/exu/exu_mul_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/deprecated/fifo_v2.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/fifo_v3.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/gray_to_binary.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/ifu/ifu.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/ifu/ifu_aln_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/ifu/ifu_bp_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/ifu/ifu_compress_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/ifu/ifu_ic_mem.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/ifu/ifu_ifc_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/ifu/ifu_mem_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lsu/lsu.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lsu/lsu_addrcheck.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lsu/lsu_bus_buffer.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lsu/lsu_bus_intf.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lsu/lsu_clkdomain.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lsu/lsu_dccm_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lsu/lsu_dccm_mem.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lsu/lsu_ecc.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lsu/lsu_lsc_ctl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lsu/lsu_stbuf.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lsu/lsu_trigger.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/lzc.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/mem.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/lib/mem_lib.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/pic/pic_ctrl.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/rr_arb_tree.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/spill_register.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/stream_register.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/swerv.sv
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/swerv_wrapper_dmi.sv
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/sync.sv
      D:/RVfpga/RFISC_V/RVfpga/src/rvfpganexys.sv
    }
      rt::read_verilog -include {
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include
    D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/include
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/gpio
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/ptc
    D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/WishboneInterconnect
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/uart
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi
    D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells
    D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/BootROM/sw
  } {
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/SweRVEh1CoreComplex/include/common_defines.vh
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/AxiToWb/axi2wb.v
      D:/RVfpga/RFISC_V/RVfpga/src/OtherSources/clk_gen_nexys.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/BootROM/dpram64.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/spi/fifo4.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/gpio/gpio_top.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/litedram_core.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/litedram_top.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/ptc/ptc_top.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/uart/raminfr.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_alu.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_bufreg.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_csr.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_ctrl.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_decode.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_mem_if.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_if.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_ram.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_ram_if.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_top.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_shift.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_state.v
      D:/RVfpga/RFISC_V/RVfpga/src/LiteDRAM/serv_1.0.2/rtl/serv_top.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/spi/simple_spi_top.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/swervolf_core.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/SystemController/swervolf_syscon.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/uart/uart_receiver.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/uart/uart_regs.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/uart/uart_rfifo.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/uart/uart_sync_flops.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/uart/uart_tfifo.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/uart/uart_top.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/uart/uart_transmitter.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Peripherals/uart/uart_wb.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/WishboneInterconnect/wb_intercon.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/BootROM/wb_mem_wrapper.v
      D:/RVfpga/RFISC_V/RVfpga/src/SweRVolfSoC/Interconnect/WishboneInterconnect/wb_intercon_1.2.2-r1/wb_mux.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top rvfpganexys
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/RVfpga/RiscV/Lab5/Lab5/.Xil/Vivado-17656-MSI/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
